name: actionlint
title: actionlint
base: core24
version: 0.12.10
summary: Static checker for GitHub Actions workflow files
description: |
  [actionlint](https://github.com/rhysd/actionlint) is a static checker for
  GitHub Actions workflow files. [Try it
  online!](https://rhysd.github.io/actionlint)

  Features:

  - **Syntax check for workflow files** to check unexpected or missing keys
    following workflow syntax
  - **Strong type check for `${{ }}` expressions** to catch several semantic
    errors like access to not existing property, type mismatches, ...
  - **Actions usage check** to check that inputs at `with:` and outputs in
    `steps.{id}.outputs` are correct
  - **Reusable workflow check** to check inputs/outputs/secrets of reusable
    workflows and workflow calls
  - **[shellcheck](https://github.com/koalaman/shellcheck) and
    [pyflakes](https://github.com/PyCQA/pyflakes) integrations** for scripts at
    `run:`
  - **Security checks**; script injection by untrusted inputs, hard-coded
    credentials
  - **Other several useful checks**; glob syntax validation, dependencies check
    for `needs:`, runner label validation, cron syntax validation, ...

  See the [full
  list](https://github.com/rhysd/actionlint/blob/main/docs/checks.md) of checks
  done by actionlint.


grade: stable
confinement: strict

platforms:
  amd64:
  arm64:
  ppc64el:
  riscv64:
  s390x:

parts:
  shellcheck:
    plugin: nil
    stage-snaps:
      - shellcheck
  pyflakes:
    plugin: nil
    build-snaps:
      - astral-uv
    build-environment:
      - VIRTUAL_ENV: $CRAFT_PART_INSTALL
    override-build: |
      uv venv $CRAFT_PART_INSTALL
      uv pip install pyflakes
  actionlint:
    plugin: go
    source: https://github.com/rhysd/actionlint.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    build-snaps:
      - go
    override-build: |
      # Workaround for https://github.com/canonical/craft-parts/issues/1416
      go install -ldflags '-X "github.com/rhysd/actionlint.installedFrom=installed from snap store (edge channel)"' ./...
apps:
  actionlint:
    command: bin/actionlint
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
    plugs:
      - home
      - removable-media
  generate-availability:
    command: bin/generate-availability
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
    plugs:
      - home
      - removable-media
      - network
  generate-popular-actions:
    command: bin/generate-popular-actions
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
    plugs:
      - network
  generate-webhook-events:
    command: bin/generate-webhook-events
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
    plugs:
      - network


